name: Build

on:
  workflow_dispatch:

  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Compile TypeScript
        run: npm run build

      - name: Install prod dependencies in dist/
        run: |
          cp package*.json dist/
          npm ci --prefix dist --omit=dev --ignore-scripts

      - name: Create ZIP artifact
        run: |
          cd dist
          zip -r ../lambda.zip .

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda-package
          path: lambda.zip
          retention-days: 1
